#!/usr/bin/env bash
# Generate audit report from detected best practice violations JSON
# Usage: ./scripts/generate-audit-report.sh <violations.json> <target-name>
#
# Parameters:
# - violations.json - Output from detect-best-practice-violations.sh
# - target-name - Name of the audited component/module (e.g., "UserService", "AuthModule")
#
# Output: Markdown audit report following assets/output-report-template.md structure
#
# Requires: jq (JSON processor)
# - macOS: brew install jq
# - Linux: apt-get install jq or yum install jq

set -euo pipefail

json_file="${1:-}"
target_name="${2:-}"

if [[ -z "$json_file" ]] || [[ -z "$target_name" ]]; then
  echo "Usage: $0 <violations.json> <target-name>" >&2
  exit 1
fi

if [[ ! -f "$json_file" ]]; then
  echo "Error: File '$json_file' not found" >&2
  exit 1
fi

if ! command -v jq &> /dev/null; then
  echo "Error: jq is required but not installed" >&2
  echo "Install with: brew install jq (macOS) or apt-get install jq (Linux)" >&2
  exit 1
fi

# Count violations by severity and category
total=$(jq 'length' "$json_file")
critical=$(jq '[.[] | select(.severity == "Critical")] | length' "$json_file")
high=$(jq '[.[] | select(.severity == "High")] | length' "$json_file")
medium=$(jq '[.[] | select(.severity == "Medium")] | length' "$json_file")
low=$(jq '[.[] | select(.severity == "Low")] | length' "$json_file")

type_safety=$(jq '[.[] | select(.category == "Type Safety")] | length' "$json_file")
safety=$(jq '[.[] | select(.category == "Safety")] | length' "$json_file")
state_mgmt=$(jq '[.[] | select(.category == "State Management")] | length' "$json_file")
return_values=$(jq '[.[] | select(.category == "Return Values")] | length' "$json_file")
code_quality=$(jq '[.[] | select(.category == "Code Quality")] | length' "$json_file")

# Generate report
cat <<EOF
# TypeScript/JavaScript Best Practices Audit: $target_name

**Date**: $(date +%Y-%m-%d)
**Target**: $target_name
**Total Violations**: $total

---

## Executive Summary

### Violation Breakdown by Severity
- **Critical**: $critical violations
- **High**: $high violations
- **Medium**: $medium violations
- **Low**: $low violations

### Violation Breakdown by Category
- **Type Safety**: $type_safety violations
- **Safety**: $safety violations
- **State Management**: $state_mgmt violations
- **Return Values**: $return_values violations
- **Code Quality**: $code_quality violations

---

## Phase 1: Detailed Findings

EOF

# Generate findings by severity (Critical -> High -> Medium -> Low)
for severity in "Critical" "High" "Medium" "Low"; do
  count=$(jq "[.[] | select(.severity == \"$severity\")] | length" "$json_file")
  if [[ $count -gt 0 ]]; then
    cat <<EOF
### $severity Severity ($count violations)

EOF
    jq -r ".[] | select(.severity == \"$severity\") |
      \"#### \" + .pattern + \"\n\n\" +
      \"**Location**: \`\" + .file + \":\(+.line)\`\n\n\" +
      \"**Category**: \" + .category + \"\n\n\" +
      \"**Impact**: \" + .expectedGain + \"\n\n\" +
      \"**Code**:\n\`\`\`typescript\n\" + .code + \"\n\`\`\`\n\n\" +
      \"**Fix**: See [references/\" + .references + \"](../references/\" + .references + \") for correct patterns.\n\n\" +
      \"---\n\"
    " "$json_file"
  fi
done

# Generate Phase 2 summary table
cat <<EOF

---

## Phase 2: Summary Table

| # | File | Line | Pattern | Severity | Category | References |
|---|------|------|---------|----------|----------|------------|
EOF

jq -r 'to_entries | .[] |
  "| " + (.key + 1 | tostring) + " | " +
  "`" + .value.file + "` | " +
  (.value.line | tostring) + " | " +
  .value.pattern + " | " +
  .value.severity + " | " +
  .value.category + " | " +
  "[" + .value.references + "](../references/" + .value.references + ") |"
' "$json_file"

cat <<EOF

---

## Next Steps

1. **Review Critical and High severity violations first** - These have the highest impact on type safety, correctness, and maintainability
2. **Load reference files as needed** - Each violation links to detailed examples showing ❌ incorrect and ✅ correct patterns
3. **Apply fixes systematically** - Work through violations by category for consistent code changes
4. **Validate changes** - Run type checker and tests after fixes to ensure correctness

---

**Generated by**: accelint-ts-best-practices skill automation
**Tool**: detect-best-practice-violations.sh + generate-audit-report.sh
EOF
